// Las categorías de la galería, en español. Las usan los scripts y el sitio.
/** Categoría en español → etiquetas en inglés que caen en ella (las de la fuente). */
export const CATEGORIAS = {
  ia: { nombre: 'Inteligencia artificial', claves: ['ai', 'chatbot', 'generative', 'transcription', 'automation'] },
  saas: { nombre: 'Software (SaaS)', claves: ['saas', 'software', 'enterprise-software', 'platform', 'crm', 'cms', 'forms', 'email', 'onboarding', 'customer-service', 'utility', 'apps', 'web-apps', 'mac'] },
  productividad: { nombre: 'Productividad y equipos', claves: ['productivity', 'collaboration', 'project-management', 'notes', 'wiki', 'remote-work', 'video-conferencing', 'communication', 'time-management', 'goal-tracking', 'workflow', 'management', 'presentations', 'video-chat', 'hr', 'recruiting', 'recruitment', 'jobs', 'job-search', 'career'] },
  finanzas: { nombre: 'Finanzas y pagos', claves: ['finance', 'fintech', 'payments', 'banking', 'investing', 'accounting', 'invoicing', 'loans', 'money-management', 'crypto', 'cryptocurrency', 'defi', 'blockchain', 'nft', 'insurance', 'credit-building', 'rental-payments', 'subscriptions'] },
  marketing: { nombre: 'Marketing y SEO', claves: ['marketing', 'seo', 'analytics', 'email-marketing', 'newsletters', 'content-marketing', 'social-media', 'social', 'content', 'content-creation', 'sales', 'website-analysis', 'market-research', 'data-analytics', 'business-intelligence', 'data', 'data-visualization'] },
  desarrollo: { nombre: 'Desarrollo', claves: ['developer-tools', 'development', 'web-development', 'api', 'programming', 'database', 'software-development', 'software-engineering', 'code', 'debugging', 'testing', 'open-source', 'cloud-computing', 'engineering', 'mobile-development', 'no-code', 'nocode', 'app-builder', 'website-builder', 'security', 'privacy', 'password-manager'] },
  diseno: { nombre: 'Diseño', claves: ['design', 'web-design', 'ui', 'ux', 'ui-design', 'ux-design', 'ux-ui', 'product-design', 'interface-design', 'design-systems', 'figma', 'prototyping', 'mockups', 'ui-kits', 'icons', 'fonts', 'typography', 'illustration', 'art', 'visual-arts', '3d-design', 'animation', 'branding', 'creative', 'creativity', 'design-inspiration', 'inspiration', 'templates', 'web-assets', 'assets', 'photo-editing', 'photography', 'screenshots', 'video', 'video-production'] },
  agencias: { nombre: 'Agencias y portafolios', claves: ['agency', 'portfolio', 'studio', 'creative-agency', 'design-studio', 'branding-agency', 'marketing-agency', 'personal', 'freelance', 'consulting', 'art-direction'] },
  tiendas: { nombre: 'Tiendas y marcas', claves: ['ecommerce', 'fashion', 'apparel', 'beauty', 'skincare', 'food', 'food-and-drink', 'beverages', 'beverage', 'coffee', 'alcohol', 'seltzer', 'home', 'home-goods', 'home-decor', 'furniture', 'luxury', 'gifts', 'accessories', 'shopping', 'grocery', 'marketplace', 'electronics', 'hardware', 'cameras', 'camera', 'plus-size', 'lifestyle'] },
  medios: { nombre: 'Medios, educación y eventos', claves: ['education', 'books', 'publishing', 'blog', 'blogging', 'entertainment', 'music', 'audio', 'gaming', 'sports', 'events', 'conference', 'webinars', 'live-streaming', 'museum', 'storytelling', 'writing', 'community', 'forum', 'research', 'reference', 'guides'] },
}
